{
  "schema_version": "1.3.0",
  "id": "GHSA-w596-4wvx-j9j6",
  "modified": "2022-10-19T07:59:30Z",
  "published": "2022-10-16T12:00:23Z",
  "aliases": [
    "CVE-2022-42969"
  ],
  "summary": "ReDoS in py library",
  "details": "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled.\n\n**NOTE:** The affected code is unlikely to be in any production use. In particular, is is *not* used by pytest, which is by far the biggest reverse dependency of the `py` library.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "1.11.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42969"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytest-dev/py/issues/287"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/pytest-dev/py"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"
    },
    {
      "type": "WEB",
      "url": "https://pypi.org/project/py"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-1333"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}