{
  "schema_version": "1.2.0",
  "id": "GHSA-gfv6-cj92-g3hx",
  "modified": "2021-09-10T20:53:56Z",
  "published": "2018-12-21T17:46:39Z",
  "aliases": [
    "CVE-2018-1000872"
  ],
  "summary": "Moderate severity vulnerability that affects pykmip",
  "details": "OpenKMIP PyKMIP version All versions before 0.8.0 contains a CWE 399: Resource Management Errors (similar issue to CVE-2015-5262) vulnerability in PyKMIP server that can result in DOS: the server can be made unavailable by one or more clients opening all of the available sockets. This attack appear to be exploitable via A client or clients open sockets with the server and then never close them. This vulnerability appears to have been fixed in 0.8.0.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pykmip"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.8.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-1000872"
    },
    {
      "type": "WEB",
      "url": "https://github.com/OpenKMIP/PyKMIP/issues/430"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-gfv6-cj92-g3hx"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/OpenKMIP/PyKMIP"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-400"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}