{
  "schema_version": "1.2.0",
  "id": "GHSA-cqf7-ff9h-7967",
  "modified": "2022-05-17T00:48:30Z",
  "published": "2022-05-17T00:48:30Z",
  "aliases": [
    "CVE-2015-5145"
  ],
  "details": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2015-5145"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/201510-06"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
    },
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/75691"
    },
    {
      "type": "WEB",
      "url": "http://www.securitytracker.com/id/1032820"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}