{
  "schema_version": "1.2.0",
  "id": "GHSA-f7cm-ccfp-3q4r",
  "modified": "2022-05-14T02:09:22Z",
  "published": "2022-05-14T02:09:22Z",
  "aliases": [
    "CVE-2014-0480"
  ],
  "details": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-0480"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2014/aug/20/security/"
    },
    {
      "type": "WEB",
      "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
    },
    {
      "type": "WEB",
      "url": "http://secunia.com/advisories/59782"
    },
    {
      "type": "WEB",
      "url": "http://secunia.com/advisories/61276"
    },
    {
      "type": "WEB",
      "url": "http://secunia.com/advisories/61281"
    },
    {
      "type": "WEB",
      "url": "http://www.debian.org/security/2014/dsa-3010"
    },
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/69425"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-20"
    ],
    "severity": "MODERATE",
    "github_reviewed": false
  }
}