{
  "schema_version": "1.4.0",
  "id": "GHSA-65fx-pmw6-rcfm",
  "modified": "2023-11-10T05:04:10Z",
  "published": "2023-08-23T09:30:12Z",
  "aliases": [
    "CVE-2023-41105"
  ],
  "summary": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
  "details": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "https://github.com/python/cpython/"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-41105"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/issues/106242"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/107981"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/107982"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/107983"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/commit/09322724319d4c23195300b222a1c0ea720af56b"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/commit/8927cf0200e56ebf74ed43f8c3fd724cd699ec22"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/commit/ccf81e1088c25a9f4464e478dc3b5c03ed7ee63b"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/commit/dd73f2f76ab1eabe92a2ca820430be723df31cde"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/commit/de33b5c662ea8d35d81ed857c6a39e34ab94c510"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/commit/ede98958810b76694cf756d305b564cd6adc1a48"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/python/cpython/"
    },
    {
      "type": "WEB",
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20231006-0015/"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-426"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2023-08-23T07:15:08Z"
  }
}