{
  "schema_version": "1.2.0",
  "id": "GHSA-6p56-wp2h-9hxr",
  "modified": "2022-02-08T20:09:24Z",
  "published": "2022-01-07T00:09:39Z",
  "aliases": [
    "CVE-2021-33430"
  ],
  "summary": "Buffer Overflow in NumPy",
  "details": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "numpy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "1.9.0"
            },
            {
              "fixed": "1.21"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33430"
    },
    {
      "type": "WEB",
      "url": "https://github.com/numpy/numpy/issues/18939"
    },
    {
      "type": "WEB",
      "url": "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/numpy/numpy"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-120"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}