{
  "schema_version": "1.4.0",
  "id": "GHSA-hgjj-fr5h-j9mv",
  "modified": "2022-05-24T16:48:28Z",
  "published": "2022-05-24T16:48:28Z",
  "aliases": [
    "CVE-2019-12903"
  ],
  "details": "Pydio Cells before 1.5.0, when supplied with a Name field in an unexpected Unicode format, fails to handle this and includes the database column/table name as pert of the error message, exposing sensitive information.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-12903"
    },
    {
      "type": "WEB",
      "url": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security"
    },
    {
      "type": "WEB",
      "url": "https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-200"
    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2019-06-20T00:15:00Z"
  }
}