{
  "schema_version": "1.4.0",
  "id": "GHSA-8fp9-43pw-56vw",
  "modified": "2023-08-15T21:10:21Z",
  "published": "2023-08-15T18:31:32Z",
  "aliases": [
    "CVE-2023-39661"
  ],
  "summary": "PandasAI vulnerable to arbitrary code execution",
  "details": "An issue in pandas-ai v.0.8.1 and before allows a remote attacker to execute arbitrary code via the `_is_jailbreak` function.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pandasai"
      },
      "ecosystem_specific": {
        "affected_functions": [
          ""
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "0.8.1"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-39661"
    },
    {
      "type": "WEB",
      "url": "https://github.com/gventuri/pandas-ai/issues/410"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/gventuri/pandas-ai"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-94"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2023-08-15T21:10:21Z",
    "nvd_published_at": null
  }
}