{
  "schema_version": "1.4.0",
  "id": "GHSA-3v79-q7ph-j75h",
  "modified": "2024-02-24T00:30:21Z",
  "published": "2024-02-24T00:30:20Z",
  "aliases": [
    "CVE-2024-27133"
  ],
  "summary": "MLflow untrusted dataset XSS leads to client-side RCE when running the recipe in Jupyter Notebook",
  "details": "Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset. This issue leads to a client-side RCE when running the recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over dataset table fields.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "mlflow"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.10.0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 2.9.2"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27133"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mlflow/mlflow/pull/10893"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/mlflow/mlflow/"
    },
    {
      "type": "WEB",
      "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-79"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-02-23T22:15:55Z"
  }
}